public class class364 {
   public static String field4020;
   public static String field4021 = "Take";
   public static String field4022 = "suspicious activity.";
   public static String field4023 = "Loaded input handler";
   public static String field4024 = "Loading - please wait.";
   public static String field4025;
   public static String field4026;
   public static String field4027 = "Discard";
   public static String field4028 = "null";
   public static String field4029;
   public static String field4030 = "The unpaid balance on your account needs";
   public static String field4031;
   public static String field4032 = "Connection lost";
   public static String field4033 = "Please wait - attempting to reestablish";
   public static String field4034;
   public static String field4035;
   public static String field4036;
   public static String field4037;
   public static String field4038;
   public static String field4039 = "Prepared sound engine";
   public static String field4040 = "Loading fonts - ";
   public static String field4041;
   public static String field4042 = "Sorry invited players only.";
   public static String field4043 = "Loaded title screen";
   public static String field4044 = " (Members)";
   public static String field4045 = "Loaded config";
   public static String field4046 = "";
   public static String field4047 = "Loaded sprites";
   public static String field4048 = "Loading textures - ";
   public static String field4049 = "Loaded textures";
   public static String field4050 = "Checking for updates - ";
   public static String field4051 = "Loading wordpack - ";
   public static String field4052 = "Press the button below to download it now.";
   public static String field4053 = "Loading interfaces - ";
   public static String field4054 = "Loaded interfaces";
   public static String field4055 = "Loading world map - ";
   public static String field4056 = "Loading config - ";
   public static String field4058;
   public static String field4059 = "Recover Account";
   public static String field4060 = "";
   public static String field4061 = "Please enter a 6-digit PIN.";
   public static String field4062 = "";
   public static String field4063 = "You have only just left another world.";
   public static String field4064 = "Your profile will be transferred in:";
   public static String field4065;
   public static String field4066 = "Connection timed out.";
   public static String field4067 = "Please try using a different world.";
   public static String field4068 = "";
   public static String field4069 = "Error connecting to server.";
   public static String field4070;
   public static String field4071 = "Please use a different world.";
   public static String field4072 = "No response from server.";
   public static String field4073 = "Please try using a different world.";
   public static String field4074 = "";
   public static String field4075 = "Your account has been involved";
   public static String field4076;
   public static String field4077 = "";
   public static String field4078;
   public static String field4079 = "world you were using has become unavailable.";
   public static String field4080 = "Please try again later.";
   public static String field4081 = "RuneScape has been updated!";
   public static String field4082 = "Please reload this page.";
   public static String field4083;
   public static String field4084 = "This world is full.";
   public static String field4085 = "to be resolved before you can play.";
   public static String field4086 = "";
   public static String field4087 = "Unable to connect.";
   public static String field4088 = "Login server offline.";
   public static String field4089 = "";
   public static String field4090 = "Login limit exceeded.";
   public static String field4091 = "Too many connections from your address.";
   public static String field4092 = "";
   public static String field4093 = "Unable to connect.";
   public static String field4094;
   public static String field4095 = "";
   public static String field4096;
   public static String field4097 = "Press 'change your password' on front page.";
   public static String field4098 = "";
   public static String field4099 = "You need a members account to login to this world.";
   public static String field4100 = "Please subscribe, or use a different world.";
   public static String field4101 = "";
   public static String field4102 = "Could not complete login.";
   public static String field4103 = "for 30 days: ";
   public static String field4104 = "";
   public static String field4105 = "";
   public static String field4106 = "Loading title screen - ";
   public static String field4107 = "";
   public static String field4108 = "Too many login attempts.";
   public static String field4109;
   public static String field4110;
   public static String field4111;
   public static String field4112 = "members world and move your character";
   public static String field4113 = "to a non-members area.";
   public static String field4114 = "Your account has been locked due to";
   public static String field4115 = "Bad session id.";
   public static String field4116 = "Please recover your account.";
   public static String field4117 = "This world is running a closed Beta.";
   public static String field4118;
   public static String field4119 = "Please use a different world.";
   public static String field4120 = "Invalid loginserver requested.";
   public static String field4121 = "Loaded world map";
   public static String field4122 = "";
   public static String field4123 = "Malformed login packet.";
   public static String field4124 = "Please try again.";
   public static String field4125 = "Please try using a different world.";
   public static String field4126 = "No reply from loginserver.";
   public static String field4127 = "Please wait 1 minute and try again.";
   public static String field4128 = "";
   public static String field4129;
   public static String field4130 = "";
   public static String field4131 = "";
   public static String field4132 = "Unexpected loginserver response.";
   public static String field4133 = "Please try using a different world.";
   public static String field4134 = "";
   public static String field4135 = "This computers address has been blocked";
   public static String field4136 = "as it was used to break our rules.";
   public static String field4137 = "";
   public static String field4138 = "";
   public static String field4139 = "Service unavailable.";
   public static String field4140 = "";
   public static String field4141 = "We suspect someone knows your password.";
   public static String field4142 = "Please enter your username/email address.";
   public static String field4143;
   public static String field4144 = "Trust this computer";
   public static String field4145 = "Either your account is still logged in, or the last";
   public static String field4146 = "";
   public static String field4147 = "Error loading your profile.";
   public static String field4148 = "in order to play the game.  Please set it";
   public static String field4149;
   public static String field4150 = "Drop";
   public static String field4151 = "Hidden";
   public static String field4152;
   public static String field4153;
   public static String field4154;
   public static String field4155;
   public static String field4156;
   public static String field4157;
   public static String field4158;
   public static String field4159;
   public static String field4160;
   public static String field4161;
   public static String field4162;
   public static String field4163;
   public static String field4164;
   public static String field4165;
   public static String field4166;
   public static String field4167;
   public static String field4168;
   public static String field4169 = "";
   public static String field4170;
   public static String field4171;
   public static String field4172;
   public static String field4173;
   public static String field4174;
   public static String field4175;
   public static String field4176;
   public static String field4177;
   public static String field4178;
   public static String field4179;
   public static String field4180;
   public static String field4181;
   public static String field4182;
   public static String field4183;
   public static String field4184;
   public static String field4185;
   public static String field4186;
   public static String field4187;
   public static String field4188;
   public static String field4189;
   public static String field4190 = "via the website, or the main game.";
   public static String field4191;
   public static String field4192 = "To access this free world, log into a";
   public static String field4193 = "Please wait 1 minute and try again.";
   public static String field4194;
   public static String field4195;
   public static String field4196 = "Loaded update list";
   public static String field4197;
   public static String field4198;
   public static String field4199;
   public static String field4200;
   public static String field4201;
   public static String field4202;
   public static String field4203;
   public static String field4204 = "Loaded wordpack";
   public static String field4205;
   public static String field4206;
   public static String field4207;
   public static String field4208;
   public static String field4209;
   public static String field4210;
   public static String field4211;
   public static String field4212;
   public static String field4213;
   public static String field4214 = "View Appeal Options";
   public static String field4215;
   public static String field4216;
   public static String field4217 = "The server is being updated.";
   public static String field4218;
   public static String field4219;
   public static String field4220;
   public static String field4221;
   public static String field4222;
   public static String field4223;
   public static String field4224;
   public static String field4225;
   public static String field4226 = "Loaded fonts";
   public static String field4227 = "Continue";
   public static String field4228 = "Please contact customer support.";
   public static String field4229 = "Select";
   public static String field4230;
   public static String field4231;
   public static String field4232;
   public static String field4233;
   public static String field4234 = "Please try using a different world.";
   public static String field4235;
   public static String field4236;
   public static String field4237;
   public static String field4238 = "";
   public static String field4239 = "Ok";
   public static String field4240;
   public static String field4241;
   public static String field4242;
   public static String field4243;
   public static String field4244;
   public static String field4245;
   public static String field4246;
   public static String field4247 = "";
   public static String field4248;
   public static String field4249;
   public static String field4250;
   public static String field4251;
   public static String field4252;
   public static String field4253;
   public static String field4254;
   public static String field4255;
   public static String field4256;
   public static String field4257;
   public static String field4258;
   public static String field4259 = "Please enter your password.";
   public static String field4260;
   public static String field4261;
   public static String field4262;
   public static String field4263;
   public static String field4264;
   public static String field4265;
   public static String field4266;
   public static String field4267 = "in serious rule breaking.";
   public static String field4268;
   public static String field4269;
   public static String field4270;
   public static String field4271;
   public static String field4272;
   public static String field4273;
   public static String field4274;
   public static String field4275;
   public static String field4276;
   public static String field4277;
   public static String field4278;
   public static String field4279;
   public static String field4280;
   public static String field4281;
   public static String field4282;
   public static String field4283;
   public static String field4284 = "Prepared visibility map";
   public static String field4285;
   public static String field4286;
   public static String field4287 = "Loading sprites - ";
   public static String field4288;
   public static String field4289;
   public static String field4290;
   public static String field4291;
   public static String field4292;
   public static String field4293 = "Your account must have a displayname set";
   public static String field4294;
   public static String field4295;
   public static String field4296;
   public static String field4297;
   public static String field4298;
   public static String field4299;
   public static String field4300;
   public static String field4301 = "Starting game engine...";
   public static String field4302;
   public static String field4303;
   public static String field4304;
   public static String field4305;
   public static String field4306;
   public static String field4307;
   public static String field4308;
   public static String field4309;
   public static String field4310;
   public static String field4311;
   public static String field4312;
   public static String field4313;
   public static String field4314;
   public static String field4315;
   public static String field4316;
   public static String field4317;
   public static String field4318;
   public static String field4319 = "Connecting to update server";
   public static String field4320;
   public static String field4321;
   public static String field4322;
   public static String field4323;
   public static String field4324 = "Please try using a different world.";
   public static String field4325 = " seconds.";
   public static String field4326;
   public static String field4327 = "You can use the Jagex Launcher to continue playing.";
   public static String field4328;
   public static String field4329;
   public static String field4330;
   static String field4057 = "Please visit the support page for assistance.";

   static {
      field4269 = field4057;
      field4250 = "Your account is currently inaccessible.";
      field4154 = "Please try again in a few minutes.";
      field4155 = "";
      field4156 = "You need to vote to play!";
      field4083 = "Visit runescape.com and vote,";
      field4158 = "and then come back here!";
      field4159 = "Sorry, but your account is not eligible to play.";
      field4160 = "For more information, please take a look at";
      field4161 = "our privacy policy.";
      field4183 = "Privacy Policy";
      field4163 = "Enter the 6-digit code generated by your";
      field4164 = "authenticator app.";
      field4171 = "";
      field4326 = "The code you entered was incorrect.";
      field4167 = "Please try again.";
      field4168 = "";
      field4129 = "Login attempt timed out.";
      field4170 = "Please try again.";
      field4166 = "";
      field4172 = "You were signed out.";
      field4173 = "Please sign in again.";
      field4174 = "";
      field4175 = "Failed to login.";
      field4111 = "Please try again.";
      field4065 = "";
      field4178 = "Unexpected server response";
      field4035 = "Please try using a different world.";
      field4180 = "";
      field4181 = " has logged in.";
      field4182 = " has logged out.";
      field4245 = "Unable to find ";
      field4277 = "Use";
      field4185 = "Examine";
      field4186 = "Attack";
      field4187 = "Choose Option";
      field4026 = " more options";
      field4189 = "Walk here";
      field4253 = "level-";
      field4191 = "skill-";
      field4037 = "Please wait...";
      field4179 = "Close";
      field4194 = " ";
      field4195 = "M";
      field4094 = "M";
      field4162 = "K";
      field4198 = "K";
      field4058 = "World";
      field4200 = "Your friend list is full. Max of 200 for free users, and 400 for members";
      field4201 = " is already on your friend list";
      field4188 = "Your ignore list is full. Max of 100 for free users, and 400 for members";
      field4203 = " is already on your ignore list";
      field4152 = "You can't add yourself to your own friend list";
      field4318 = "You can't add yourself to your own ignore list";
      field4153 = "Please remove ";
      field4070 = " from your ignore list first";
      field4208 = "Please remove ";
      field4209 = " from your friend list first";
      field4210 = "yellow:";
      field4211 = "red:";
      field4212 = "green:";
      field4213 = "cyan:";
      field4309 = "purple:";
      field4215 = "white:";
      field4216 = "flash1:";
      field4029 = "flash2:";
      field4264 = "flash3:";
      field4271 = "glow1:";
      field4076 = "glow2:";
      field4221 = "glow3:";
      field4222 = "rainbow:";
      field4223 = "pattern";
      field4110 = "wave:";
      field4096 = "wave2:";
      field4206 = "shake:";
      field4237 = "scroll:";
      field4118 = "slide:";
      field4199 = "RuneScape is loading - please wait...";
      field4230 = "";
      field4025 = "Enter your username/email & password.";
      field4232 = "";
      field4233 = "Warning!";
      field4306 = "This is a <col=ff0000>PvP<col=ffffff> world.";
      field4285 = "Players can attack each other";
      field4236 = "almost everywhere.";
      field4231 = "This is a <col=ffff00>High Risk<col=ffffff> world.";
      field4224 = "The Protect Item prayer will";
      field4036 = "not work on this world.";
      field4240 = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
      field4241 = "Players can attack each other almost everywhere";
      field4283 = "and the Protect Item prayer won't work.";
      field4243 = "This is a <col=00ffff>Beta<col=ffffff> world.";
      field4244 = "Your normal account will not be affected.";
      field4291 = "";
      field4246 = "Authenticator";
      field4202 = "<u=ff>Can't Log In?</u>";
      field4316 = "";
      field4249 = "Connecting to server...";
      field4292 = "";
      field4251 = "The game servers are currently being updated.";
      field4252 = "Please wait a few minutes and try again.";
      field4205 = "";
      field4254 = "";
      field4255 = "You were disconnected from the server.";
      field4256 = "";
      field4257 = "Login: ";
      field4258 = "Password: ";
      field4149 = "PIN: ";
      field4260 = "Welcome to RuneScape";
      field4261 = "New User";
      field4262 = "Existing User";
      field4263 = "Login";
      field4177 = "Cancel";
      field4265 = "Remember username";
      field4266 = "Hide username";
      field4038 = "Incorrect username or password.";
      field4268 = "If you have upgraded to a Jagex Account, you";
      field4165 = "need to log in using the <u=ffd200><col=ffd200>Jagex Launcher</col></u> instead.";
      field4270 = "Try again";
      field4220 = "Forgotten password?";
      field4272 = "Forgotten your password?";
      field4273 = "Username/email: ";
      field4274 = "Recover";
      field4275 = "Back";
      field4276 = "Can't login? Click here.";
      field4197 = "Still having trouble logging in?";
      field4278 = "Having trouble logging in?";
      field4279 = "";
      field4280 = "Page has opened in the browser.";
      field4281 = "";
      field4282 = "Please enter your username.";
      field4242 = "If you created your account after November";
      field4218 = "2010, this will be the creation email address.";
      field4031 = field4279;
      field4286 = field4280;
      field4157 = field4281;
      field4288 = "";
      field4289 = "Error connecting to server.";
      field4290 = "";
      field4235 = "The part of the website you are trying";
      field4219 = "to connect to is offline at the moment.";
      field4303 = "Please try again later.";
      field4294 = "Sorry, there was an error trying to";
      field4295 = "log you in to this part of the website.";
      field4296 = "Please try again later.";
      field4297 = "";
      field4298 = "Error connecting to server.";
      field4299 = "";
      field4300 = "You must enter a valid login to proceed. For accounts";
      field4184 = "created after 24th November 2010, please use your";
      field4302 = "email address. Otherwise please use your username.";
      field4041 = "Your date of birth isn't set.";
      field4304 = "Please verify your account status by";
      field4305 = "setting your date of birth.";
      field4109 = "Set Date of Birth";
      field4307 = "Your date of birth information is waiting";
      field4308 = "to be reviewed by our staff.";
      field4248 = "It will be processed shortly.";
      field4310 = "Before using this app, please read and accept our";
      field4311 = "<col=ffd200>terms of use</col>, <col=ffd200>privacy policy</col>, and <col=ffd200>end user licence</col>";
      field4312 = "<col=ffd200>agreement (EULA)</col>.";
      field4313 = "By accepting, you agree to these documents.";
      field4314 = "You must accept our terms of use, privacy policy,";
      field4315 = "and end user licence agreement to continue.";
      field4207 = "Accept";
      field4317 = "Decline";
      field4225 = "Select a world";
      field4176 = "Members only world";
      field4320 = "Free world";
      field4321 = "World";
      field4322 = "Players";
      field4323 = "Location";
      field4020 = "Type";
      field4078 = "OFF";
      field4143 = "FULL";
      field4034 = "Loading...";
      field4328 = "Click to switch";
      field4329 = "Download Launcher";
      field4330 = "https://oldschool.runescape.com/launcher";
   }

   class364() throws Throwable {
   }

   static final float method6635(int var0) {
      float var2 = 10075.0F - (float)var0;
      return (var2 * 1.0075567F - 75.56675F) / var2;
   }

   static int method6636(int var0) {
      class76 var2 = (class76)class119.field1135.method8096((long)var0);
      if (null == var2) {
         return -1;
      } else {
         return class119.field1136.field4445 == var2.field4848 ? -1 : ((class76)var2.field4848).field625;
      }
   }
}
